# Generated by Django 5.1.4 on 2024-12-07 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Varieties_object',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.varieties'),
        ),
    ]
